name: Packer Image Build

on:
  push:
    tags: ["v[0-9].[0-9]+.[0-9]+"]
    branches:
      - "main"
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  AWS_ROLE: arn:aws:iam::182402351974:role/github-packer

permissions:
  id-token: write
  contents: read

jobs:
  ImageBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repo
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          role-session-name: github-packer
          aws-region: ${{ env.AWS_REGION }}

      - name: Packer init
        uses: hashicorp/packer-github-actions@master
        with:
          command: init

      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: image.pkr.hcl
    
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false"
          target: image.pkr.hcl
          working_directory: .
        env:
          PACKER_LOG: 1